trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller
    displayName: install terraform
    inputs:
        terraformVersion: 1.1.0

- script: |
    terraform init
    terraform plan -var 'aws_access_key=${parameters.AWS_ACCESS_KEY}' -var 'aws_access_secret=${parameters.AWS_ACCESS_SECRET}' -input=false
    terraform apply -auto-approve -input=false
  displayName: TF Init Plan Apply