# build.yaml

jobs:
- job: build
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: TerraformInstaller@0
    displayName: install terraform
    inputs:
      terraformVersion: 1.1.0
  - script: |
      cd tf
      terraform init
      terraform plan -var 'aws_access_key=${parameters.AWS_ACCESS_KEY}' -var 'aws_access_secret=${parameters.AWS_ACCESS_SECRET}' -input=false
      terraform apply -auto-approve -input=false
    displayName: TF Init Plan Apply